version: "3"
services:
  spa:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    container_name: spa
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
    command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
