version: '3.7'
services: 
    api:
        container_name: api
        build: 
            context: ./api
        environment: 
          - ASPNETCORE_URLS=http://+:80            
        ports: 
          - "5005:80"
    frontend:
        container_name: frontend
        build: 
            context: ./frontend
        ports: 
          - "5006:80"